# Generated by Django 2.1.7 on 2020-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='getplan_comment',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='progress',
            name='getplan_sentence',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='sentence'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B1_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B1_YN',
            field=models.BooleanField(default=False, verbose_name='성건강 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B2_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B2_YN',
            field=models.BooleanField(default=False, verbose_name='관계 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B3_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B3_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타 이름'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B3_YN',
            field=models.BooleanField(default=False, verbose_name='기타 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C1_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C1_YN',
            field=models.BooleanField(default=False, verbose_name='먹거리 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C2_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C2_YN',
            field=models.BooleanField(default=False, verbose_name='물품 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C3_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C3_YN',
            field=models.BooleanField(default=False, verbose_name='교통비 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C4_C',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C4_YN',
            field=models.BooleanField(default=False, verbose_name='자원연계 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C5_TC',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='총비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C5_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
    ]
