# Generated by Django 2.1.7 on 2020-06-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_ctrs_ct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='CT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Planning', verbose_name='CT'),
        ),
    ]
