# Generated by Django 2.1.7 on 2020-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0004_auto_20200607_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A1_C',
            field=models.IntegerField(blank=True, default=0, verbose_name='비용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A2_C',
            field=models.IntegerField(blank=True, default=0, verbose_name='비용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A3_C',
            field=models.IntegerField(blank=True, default=0, verbose_name='비용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A4_C',
            field=models.IntegerField(blank=True, default=0, verbose_name='비용'),
        ),
    ]
