# Generated by Django 2.1.7 on 2020-06-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0006_auto_20200607_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='Progress_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='progress',
            name='CT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Intake', verbose_name='CT'),
        ),
    ]
