# Generated by Django 2.1.7 on 2020-06-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0007_auto_20200608_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrs',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 작성일'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 작성일'),
        ),
    ]
