# Generated by Django 2.1.7 on 2020-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0008_auto_20200608_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrs',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 수정날짜'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 수정날짜'),
        ),
    ]
