# Generated by Django 2.1.7 on 2020-06-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0010_auto_20200608_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrs',
            name='sum_1',
        ),
    ]
