# Generated by Django 2.1.7 on 2020-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0011_remove_ctrs_sum_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrs',
            name='sum_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='개인영역 Sum'),
        ),
    ]
