# Generated by Django 2.1.7 on 2020-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0012_ctrs_sum_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A1_C',
            new_name='inmedical_A1_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A1_Text',
            new_name='inmedical_A1_Text_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A1_select2',
            new_name='inmedical_A1_select_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A2_C',
            new_name='inmedical_A2_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A2_Text',
            new_name='inmedical_A2_Text_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A3_C',
            new_name='inmedical_A3_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A3_Text',
            new_name='inmedical_A3_Text_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A4_C',
            new_name='inmedical_A4_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A4_Text',
            new_name='inmedical_A4_Text_1',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='inmedical_A1_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='inmedical_A2_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='inmedical_A3_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='inmedical_A4_select',
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A1_YN_1',
            field=models.BooleanField(default=False, verbose_name='치과 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A1_select_2',
            field=models.CharField(blank=True, choices=[('스케일링', '스케일링'), ('보철', '보철'), ('충치', '충치'), ('기타', '기타')], default='', max_length=4, verbose_name='치과 진료명'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A2_YN_1',
            field=models.BooleanField(default=False, verbose_name='여성의학 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A3_YN_1',
            field=models.BooleanField(default=False, verbose_name='한방의학 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A4_YN_1',
            field=models.BooleanField(default=False, verbose_name='가정의학 여부'),
        ),
    ]
