# Generated by Django 2.1.7 on 2020-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0013_auto_20200608_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='inmedical_A1_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A1_Text_2',
            field=models.CharField(blank=True, default='없음', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A1_YN_2',
            field=models.BooleanField(default=False, verbose_name='치과(야간) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A2_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A2_Text_2',
            field=models.CharField(blank=True, default='없음', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A2_YN_2',
            field=models.BooleanField(default=False, verbose_name='여성의학(야간) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A3_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A3_Text_2',
            field=models.CharField(blank=True, default='없음', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A3_YN_2',
            field=models.BooleanField(default=False, verbose_name='한방의학(야간) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A4_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A4_Text_2',
            field=models.CharField(blank=True, default='없음', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A4_YN_2',
            field=models.BooleanField(default=False, verbose_name='가정의학(야간) 여부'),
        ),
    ]
