# Generated by Django 2.1.7 on 2020-06-08 13:25

from django.db import migrations
import progression.models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0014_auto_20200608_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A1_YN_1',
            field=progression.models.CustomBooleanField(default=False, verbose_name='치과 여부'),
        ),
    ]
