# Generated by Django 2.1.7 on 2020-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0016_auto_20200609_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='각종검사 SUM'),
        ),
    ]
