# Generated by Django 2.1.7 on 2020-06-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0017_progress_inmedical_a_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='inmedical_A_sum',
            new_name='inmedical_B_sum',
        ),
    ]
