# Generated by Django 2.1.7 on 2020-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0018_auto_20200609_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='incase_A_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='상담 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='1:1교육 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='기초생활지원 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='진료 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_C_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='약지급 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_D_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방접종 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_E_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='외부병원 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_F_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방의학 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_G_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='의료상담 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_A_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='정신보건 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_B_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리검사 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_C_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리정서지원 SUM'),
        ),
    ]
