# Generated by Django 2.1.7 on 2020-06-08 20:22

from django.db import migrations, models
import progression.models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0019_auto_20200609_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A2_C',
            new_name='incase_A1_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A1_C',
            new_name='incase_A1_C_2',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A1_Text',
            new_name='incase_A1_Text_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A2_Text',
            new_name='incase_A1_Text_2',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A3_C',
            new_name='incase_A2_C_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A4_C',
            new_name='incase_A2_C_2',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A3_Text',
            new_name='incase_A2_Text_1',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='incase_A4_Text',
            new_name='incase_A2_Text_2',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='incase_A1_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='incase_A2_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='incase_A3_select',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='incase_A4_select',
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A1_YN_1',
            field=progression.models.CustomBooleanField(default=False, verbose_name='대면 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A1_YN_2',
            field=progression.models.CustomBooleanField(default=False, verbose_name='대면(수강명령) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A2_YN_1',
            field=progression.models.CustomBooleanField(default=False, verbose_name='심층 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A2_YN_2',
            field=progression.models.CustomBooleanField(default=False, verbose_name='심층(수강명령) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_C_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_YN_1',
            field=progression.models.CustomBooleanField(default=False, verbose_name='전화 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A3_YN_2',
            field=progression.models.CustomBooleanField(default=False, verbose_name='전화(수강명령) 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_C_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_C_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_YN_1',
            field=progression.models.CustomBooleanField(default=False, verbose_name='SNS 여부'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_A4_YN_2',
            field=progression.models.CustomBooleanField(default=False, verbose_name='SNS(수강명령) 여부'),
        ),
    ]
