# Generated by Django 2.1.7 on 2020-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0021_auto_20200609_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='incase_A_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='상담 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_B_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='1:1교육 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='incase_C_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='기초생활지원 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='진료 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_B_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='각종검사 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_C_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='약지급 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_D_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방접종 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_E_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='외부병원 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_F_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방의학 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_G_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='의료상담 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_A_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='정신보건 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_B_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리검사 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmental_C_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리정서지원 cost'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey10_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력가해1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey10_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력가해2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey10_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력가해3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey11_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='정신건강1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey11_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='정신건강2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey11_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='정신건강3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey11_4',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='정신건강4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='개인1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='개인2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='개인3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_4',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='개인4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_5',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='개인5'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey2_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='가정1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey2_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='가정2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey2_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='가정3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey2_4',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='가정4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey2_5',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='가정5'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey3_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='또래 및 학교1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey3_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='또래 및 학교2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey3_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='또래 및 학교3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey3_4',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='또래 및 학교4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey3_5',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='또래 및 학교5'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_1',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='지지체계1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_2',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='지지체계2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_3',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='지지체계3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_4',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='지지체계4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_1',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='성건강_공통1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성건강_공통2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_3',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='성건강_공통3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_4',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성건강_공통4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_5',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='성건강_공통5'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey6_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성건강_성관계1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey6_2',
            field=models.IntegerField(blank=True, choices=[(5, '1'), (4, '2'), (3, '3'), (2, '4'), (1, '5'), (0, '9')], null=True, verbose_name='성건강_성관계2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey6_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성건강_성관계3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey7_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성폭력1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey7_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성폭력2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey7_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='성폭력3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey9_1',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력피해1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey9_2',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력피해2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey9_3',
            field=models.IntegerField(blank=True, choices=[(0, '9'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='폭력피해3'),
        ),
    ]
