# Generated by Django 2.1.7 on 2020-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0022_auto_20200609_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_1_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='치과 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_1_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='치과 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_2_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='여성의학 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_2_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='여성의학 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_3_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='한방의학 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_3_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='한방의학 SUM'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_4_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='가정의학 cost'),
        ),
        migrations.AddField(
            model_name='progress',
            name='inmedical_A_4_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='가정의학 SUM'),
        ),
    ]
