# Generated by Django 2.1.7 on 2020-06-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0023_auto_20200612_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A1_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A1_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A2_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A2_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A3_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A3_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A4_Text_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='inmedical_A4_Text_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
    ]
