# Generated by Django 2.1.7 on 2020-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0026_auto_20200612_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='개인1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='개인2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='개인3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='개인4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey1_5',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='개인5'),
        ),
    ]
