# Generated by Django 2.1.7 on 2020-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0027_auto_20200616_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrs',
            name='sum_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='가정 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey2_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='가정1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey2_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='가정2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey2_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='가정3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey2_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='가정4'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey2_5',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='가정5'),
        ),
    ]
