# Generated by Django 2.1.7 on 2020-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0028_auto_20200616_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrs',
            name='ctrs_comment',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Commnet'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='ctrs_sentence',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='오늘의 한줄'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='폭력가해 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='정신건강 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='또래 및 학교 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='지지체계 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='성건강_공통 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='성건강_성관계 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='성폭력 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='sum_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='폭력피해 Sum'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey10_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력가해1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey10_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력가해2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey10_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력가해3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey11_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='정신건강1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey11_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='정신건강2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey11_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='정신건강3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey11_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='정신건강4'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey3_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='또래 및 학교1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey3_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='또래 및 학교2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey3_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='또래 및 학교3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey3_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='또래 및 학교4'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey3_5',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='또래 및 학교5'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey4_1',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='지지체계1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey4_2',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='지지체계2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey4_3',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='지지체계3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey4_4',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='지지체계4'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey5_1',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='성건강_공통1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey5_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_공통2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey5_3',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='성건강_공통3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey5_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_공통4'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey5_5',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='성건강_공통5'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey6_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_성관계1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey6_2',
            field=models.IntegerField(blank=True, choices=[(5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (0, 0)], default=0, null=True, verbose_name='성건강_성관계2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey6_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_성관계3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey7_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성폭력1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey7_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성폭력2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey7_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성폭력3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey9_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력피해1'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey9_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력피해2'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='survey9_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='폭력피해3'),
        ),
        migrations.AddField(
            model_name='ctrs',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
