# Generated by Django 2.1.7 on 2020-06-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0029_auto_20200616_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='지지체계1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='지지체계2'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='지지체계3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey4_4',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='지지체계4'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_1',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_공통1'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_3',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_공통3'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey5_5',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_공통5'),
        ),
        migrations.AlterField(
            model_name='ctrs',
            name='survey6_2',
            field=models.IntegerField(blank=True, choices=[(0, '비해당'), (1, '전혀 그렇지 않다'), (2, '그렇지 않다'), (3, '보통이다'), (4, '그렇다'), (5, '매우 그렇다')], default=0, null=True, verbose_name='성건강_성관계2'),
        ),
    ]
