# Generated by Django 2.1.7 on 2020-06-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progression', '0030_auto_20200616_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrs',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='상담자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='상담자'),
            preserve_default=False,
        ),
    ]
