# Generated by Django 2.1.7 on 2020-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='내담자 이름')),
                ('reg', models.DateField(null=True, verbose_name='등록날짜')),
                ('coun', models.CharField(blank=True, choices=[('이성영', '이성영'), ('정현재', '정현재'), ('김현정', '김현정'), ('문보라', '문보라'), ('박지숙', '박지숙'), ('김수미', '김수미'), ('강주연', '강주연'), ('노미나', '노미나'), ('곽은영', '곽은영')], default='', max_length=3, null=True, verbose_name='최초상담자')),
                ('gender', models.CharField(blank=True, choices=[('남자', '남자'), ('여자', '여자')], default='', max_length=2, null=True, verbose_name='성별')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='연령')),
                ('status', models.CharField(blank=True, choices=[('진행', '진행'), ('종결', '종결')], default='', max_length=2, null=True, verbose_name='진행 상황')),
            ],
            options={
                'verbose_name': '내담자목록',
                'verbose_name_plural': '내담자목록',
                'db_table': 'client',
            },
        ),
    ]
