# Generated by Django 2.1.7 on 2020-06-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_planning_medical_a_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='medical_A_sum',
        ),
    ]
