# Generated by Django 2.1.7 on 2020-06-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_planning_medical_a_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='medical_A_sum',
        ),
        migrations.AddField(
            model_name='planning',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 작성일'),
        ),
    ]
