# Generated by Django 2.1.7 on 2020-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200608_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='medical_B1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='여성의학 검사 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B1_YN',
            field=models.BooleanField(default=False, verbose_name='여성의학 검사 여부'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기초검사 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B2_YN',
            field=models.BooleanField(default=False, verbose_name='기초검사 여부'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='항체검사 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B3_YN',
            field=models.BooleanField(default=False, verbose_name='항체검사 여부'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B4_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타검사명'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타검사 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_B4_YN',
            field=models.BooleanField(default=False, verbose_name='기타검사 여부'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='치료제 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='치료제 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='치료제 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='영양제 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='영양제 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='영양제 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='임신테스트기 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='임신테스트기 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='임신테스트기 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C4_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타1 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C4_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타1 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C4_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타1 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타1 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C5_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타2 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C5_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타2 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C5_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타2 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_C5_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타2 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D1_Num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='간염예방접종 차수'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='간염예방접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D2_Num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='자궁경부암접종 차수'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='자궁경부암접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='독감예방접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D3_YN',
            field=models.BooleanField(default=False, verbose_name='독감예방 여부'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D4_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타1 접종 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D4_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타1 접종 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타1 접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D5_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타2 접종 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D5_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타2 접종 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D5_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타2 접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D6_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타3 접종 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D6_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타3 접종 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_D6_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타3 접종 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(치과) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(치과) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='외부(치과) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(여성) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(여성) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='외부(여성) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(기타) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E3_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='외부(기타) 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='외부(기타) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_E3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='외부(기타) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='잇솔질 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='잇솔질 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='잇솔질 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='안경지원 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='안경지원 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='안경지원 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='몸펴기 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='몸펴기 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='몸펴기 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F4_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='예방(기타) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F4_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='예방(기타) 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F4_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='예방(기타) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='medical_F4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='예방(기타) 내용'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Address1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Address2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='현주거지'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Fam_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타내용'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Institute',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='의뢰기관'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Res_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타내용'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Route_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타내용'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='Ssgrade_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타내용'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_A1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='치과 내용'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_A2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='여성의학 내용'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_A3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='한방의학 내용'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_A4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='가정의학 내용'),
        ),
    ]
