# Generated by Django 2.1.7 on 2020-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200608_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='mental_A1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='정신(대면) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_A1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='정신(대면) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_A1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='정신(대면) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_A2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='정신(전화) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_A2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='정신(전화) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_A2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='정신(전화) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_B1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='종합심리검사 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_B1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_B2_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_B2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_B2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='정신(전화) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='원예 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='원예 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='원예 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='몸치유 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='몸치유 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='몸치유 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C3_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mental_C3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타 내용'),
        ),
    ]
