# Generated by Django 2.1.7 on 2020-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200608_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='case_A1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(대면) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(대면) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='사례(대면) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(심층) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(심층) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='사례(심층) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(전화) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(전화) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='사례(전화) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A4_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(SNS) 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A4_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사례(SNS) 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_A4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='사례(SNS) 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='성건강 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='성건강 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='성건강 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='관계 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='관계 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='관계 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B3_Name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='기타 이름'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='기타 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_B3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C1_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='먹거리 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C1_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='먹거리 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C1_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C2_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='물품 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C2_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='물품 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C2_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='물품 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C3_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='교통비 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C3_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='교통비 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C3_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='교통비 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C4_MF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='자원연계 월빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C4_TF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='자원연계 총빈도'),
        ),
        migrations.AddField(
            model_name='planning',
            name='case_C4_Text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='자원연계 내용'),
        ),
        migrations.AddField(
            model_name='planning',
            name='setplan_comment',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='planning',
            name='setplan_sentence',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='sentence'),
        ),
    ]
