# Generated by Django 2.1.7 on 2020-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200608_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='medical_D3_YN',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='독갑예방접종 총빈도'),
        ),
    ]
