# Generated by Django 2.1.7 on 2020-06-08 17:38

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200609_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='medical_B1_YN',
            field=user.models.CustomBooleanField(default=False, verbose_name='여성의학 검사 여부'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_B2_YN',
            field=user.models.CustomBooleanField(default=False, verbose_name='기초검사 여부'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_B3_YN',
            field=user.models.CustomBooleanField(default=False, verbose_name='항체검사 여부'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='medical_B4_YN',
            field=user.models.CustomBooleanField(default=False, verbose_name='기타검사 여부'),
        ),
    ]
