# Generated by Django 2.1.7 on 2020-06-15 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_intake_counselor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='counselor',
        ),
        migrations.AddField(
            model_name='planning',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
