# Generated by Django 2.1.7 on 2020-06-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200616_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='counselor',
        ),
    ]
